name: Android APK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Give permission
        run: chmod +x gradlew || true

      - name: Build APK
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: |
            **/*.apk
